version: '3.4'

services:
  cortex.subscriptions.in.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./var.env
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - /C/ei8/avatars/prod/sample:/C/db
networks:
    default:
        external:
            name: sample_default